services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d backend"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s

  calendar:
    build:
      context: ..
      dockerfile: build/Dockerfile.calendar
    ports:
      - "8888:8080"
    depends_on:
      postgres:
        condition: service_healthy

  calendar_scheduler:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: build/Dockerfile.calendar_scheduler
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      calendar:
        condition: service_started

  calendar_sender:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: build/Dockerfile.sender
    depends_on:
      rabbitmq:
        condition: service_healthy

