// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hw12_13_14_15_calendar/internal/server (interfaces: Application)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_application.go -package=mocks github.com/hw12_13_14_15_calendar/internal/server Application
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/hw12_13_14_15_calendar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockApplication is a mock of Application interface.
type MockApplication struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationMockRecorder
	isgomock struct{}
}

// MockApplicationMockRecorder is the mock recorder for MockApplication.
type MockApplicationMockRecorder struct {
	mock *MockApplication
}

// NewMockApplication creates a new mock instance.
func NewMockApplication(ctrl *gomock.Controller) *MockApplication {
	mock := &MockApplication{ctrl: ctrl}
	mock.recorder = &MockApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplication) EXPECT() *MockApplicationMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockApplication) CreateEvent(ctx context.Context, event domain.Event) (domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, event)
	ret0, _ := ret[0].(domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockApplicationMockRecorder) CreateEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockApplication)(nil).CreateEvent), ctx, event)
}

// DeleteEvent mocks base method.
func (m *MockApplication) DeleteEvent(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockApplicationMockRecorder) DeleteEvent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockApplication)(nil).DeleteEvent), ctx, id)
}

// GetEvent mocks base method.
func (m *MockApplication) GetEvent(ctx context.Context, id string) (domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", ctx, id)
	ret0, _ := ret[0].(domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockApplicationMockRecorder) GetEvent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockApplication)(nil).GetEvent), ctx, id)
}

// ListOnDay mocks base method.
func (m *MockApplication) ListOnDay(ctx context.Context, userID string, day time.Time) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOnDay", ctx, userID, day)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOnDay indicates an expected call of ListOnDay.
func (mr *MockApplicationMockRecorder) ListOnDay(ctx, userID, day any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOnDay", reflect.TypeOf((*MockApplication)(nil).ListOnDay), ctx, userID, day)
}

// ListOnMonth mocks base method.
func (m *MockApplication) ListOnMonth(ctx context.Context, userID string, monthStart time.Time) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOnMonth", ctx, userID, monthStart)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOnMonth indicates an expected call of ListOnMonth.
func (mr *MockApplicationMockRecorder) ListOnMonth(ctx, userID, monthStart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOnMonth", reflect.TypeOf((*MockApplication)(nil).ListOnMonth), ctx, userID, monthStart)
}

// ListOnWeek mocks base method.
func (m *MockApplication) ListOnWeek(ctx context.Context, userID string, weekStart time.Time) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOnWeek", ctx, userID, weekStart)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOnWeek indicates an expected call of ListOnWeek.
func (mr *MockApplicationMockRecorder) ListOnWeek(ctx, userID, weekStart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOnWeek", reflect.TypeOf((*MockApplication)(nil).ListOnWeek), ctx, userID, weekStart)
}

// UpdateEvent mocks base method.
func (m *MockApplication) UpdateEvent(ctx context.Context, event domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockApplicationMockRecorder) UpdateEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockApplication)(nil).UpdateEvent), ctx, event)
}
