logger:
  level: "info"

http:
  host: "127.0.0.1"
  port: 8080

storage:
  type: "memory"
  db:
    host: "localhost"
    port: 5435
    user: "postgres"
    password: "password"
    dbname: "backend"
    sslmode: "disable"
